/**
 * Site configuration.
 *
 * LETTER_ZIP_WORKER_URL is the Cloudflare Worker HTTPS endpoint that streams
 * the latest letters.zip generated by GitHub Actions. It is intentionally a
 * clearly-marked placeholder: replace it once the Worker is deployed, or set
 * the HTML attribute data-worker-url in index.html without touching JS.
 *
 * No Cloudflare account id, zone id or API token is ever stored in this repo.
 */
window.SITE_CONFIG = {
  LETTER_ZIP_WORKER_URL: "https://happyweb-letter-download.happyweb-jy1004.workers.dev/letters.zip",
  SERVER_TIME_URL: "https://happyweb-letter-download.happyweb-jy1004.workers.dev/time",
};
